version: '2'
services:
 glassfish:
   build: .
   volumes:
    - ./www:/var/www/html
    - ./conf:/etc/nginx
   ports:
    - "8080:8080"
    - "4848:4848"
   environment:
    - ADMIN_PASSWORD=vulhub_default_password